// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/_Client/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  Graph:  require('./Graph'),
  Graph2: require('./Graph2'),
  Home:   require('./Home')
});
require('./PagePart');
require('./Partials');
require('./Widgets');