// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/_Client/Components/namespace.js

module.exports = require('../namespace').addNamespace(
  'Components',
  class Components extends Neptune.PackageNamespace {}
);
require('./PagePart/namespace');
require('./Partials/namespace');
require('./Widgets/namespace');