// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/_Client/Components/Partials/index.js

(module.exports = require('./namespace'))

.addModules({
  Bar:              require('./Bar'),
  BarLib:           require('./BarLib'),
  GraphStatePicker: require('./GraphStatePicker'),
  HoverLegend:      require('./HoverLegend'),
  Legend:           require('./Legend'),
  PageSelector:     require('./PageSelector'),
  StandardImport:   require('./StandardImport')
});