// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/_Client/index.js

(module.exports = require('./namespace'))

.addModules({
  Main:           require('./Main'),
  Presets:        require('./Presets'),
  StandardImport: require('./StandardImport')
});
require('./Components');
require('./Models');