// generated by Neptune Namespaces v4.x.x
// file: ArtAppKitBoilerPlate/index.js

(module.exports = require('./namespace'))

.addModules({
  GraphFunctions: require('./GraphFunctions'),
  Lib:            require('./Lib'),
  Main:           require('./Main'),
  StandardImport: require('./StandardImport')
});
require('./Components');
require('./Models');