// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/_Client/Components/PagePart/index.js

(module.exports = require('./namespace'))

.addModules({
  PageBottom:     require('./PageBottom'),
  PhoneBottom:    require('./PhoneBottom'),
  StandardImport: require('./StandardImport')
});