// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/_Client/Components/PagePart/namespace.js

module.exports = require('../namespace').addNamespace(
  'PagePart',
  class PagePart extends Neptune.PackageNamespace {}
);
