// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/_Client/Components/Widgets/index.js

(module.exports = require('./namespace'))

.addModules({
  Button:      require('./Button'),
  VersionInfo: require('./VersionInfo'),
  VinculumBar: require('./VinculumBar')
});