// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/index.js

(module.exports = require('./namespace'))

.addModules({
  GraphFunctions: require('./GraphFunctions'),
  Lib:            require('./Lib'),
  Main:           require('./Main'),
  Presets:        require('./Presets'),
  StandardImport: require('./StandardImport')
});
require('./Components');
require('./Models');