// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Covid19Statistics',
  (class Covid19Statistics extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Components/namespace');
require('./Models/namespace');