// generated by Neptune Namespaces v4.x.x
// file: tests/Covid19Statistics/index.js

(module.exports = require('./namespace'))

.addModules({
  DataLib: require('./DataLib'),
  Lib:     require('./Lib')
});