// generated by Neptune Namespaces v4.x.x
// file: tests/Covid19Statistics/namespace.js

module.exports = require('../namespace').addNamespace(
  'Covid19Statistics',
  (class Covid19Statistics extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
