// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  Bar:    require('./Bar'),
  Button: require('./Button'),
  Graph:  require('./Graph'),
  Home:   require('./Home')
});