// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  Graph: require('./Graph'),
  Home:  require('./Home')
});
require('./PagePart');
require('./Partials');
require('./Widgets');