// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/Components/namespace.js

module.exports = require('../namespace').addNamespace(
  'Components',
  class Components extends Neptune.PackageNamespace {}
);
