// generated by Neptune Namespaces v4.x.x
// file: Covid19Statistics/_Client/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  Clock:      require('./Clock'),
  CovidData:  require('./CovidData'),
  GraphState: require('./GraphState')
});