name: Update Data

on:
  schedule:
    - cron: "0 8 * * 4"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Update Data
        run: npm run update

      - name: Git Commit Push
        run: |
          git config --global user.email "shanebdavis@gmail.com"
          git config --global user.name "Shane Brinkman-Davis Delamore"
          git commit . -m "Update data via GitHub Action"
          git push

      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: Shane Brinkman-Davis Delamore
      #     author_email: shanebdavis@gmail.com
      #     message: "Update data via GitHub Action"
      #     add: "."
